#!/usr/bin/env node
/**
 * Vendors the game's typefaces into `src/assets/fonts/`.
 *
 * Self-hosting rather than linking Google Fonts buys three things that matter
 * here: no flash of fallback type on the title screen, byte-identical
 * screenshots for the visual review loop, and a game that still looks right
 * with no network. Emits `src/styles/fonts.css` with the @font-face rules.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const OUT_DIR = path.join(ROOT, "src", "assets", "fonts");
const CSS_OUT = path.join(ROOT, 'src', 'styles', 'fonts.css');

/** Chrome UA string, so Google serves woff2 rather than legacy formats. */
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const FAMILIES = [
  { name: 'Cormorant Garamond', spec: 'Cormorant+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,400;1,600' },
  { name: 'Crimson Pro', spec: 'Crimson+Pro:ital,wght@0,400;0,600;1,400;1,600' },
  { name: 'Inter Tight', spec: 'Inter+Tight:wght@400;500;600' },
  // Wren's pen. Caveat is a 2010s felt-tip casual script and the single most
  // recognisable "handwriting font" on the web; on a conservator's casebook it
  // read as a costume. This is a ballpoint hand with real pressure variation
  // and a baseline that will not sit still, which is what a nineteen-year-old
  // writing on a moving boat actually produces. Caveat stays vendored as the
  // fallback so nothing goes to a system cursive if this ever fails to load.
  { name: 'Nothing You Could Do', spec: 'Nothing+You+Could+Do' },
  { name: 'Caveat', spec: 'Caveat:wght@400;600' },
  { name: 'IBM Plex Mono', spec: 'IBM+Plex+Mono:wght@400;500' },
];

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const blocks = [];

  for (const fam of FAMILIES) {
    const url = `https://fonts.googleapis.com/css2?family=${fam.spec}&display=swap`;
    const res = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error(`${fam.name}: CSS fetch failed ${res.status}`);
    let css = await res.text();

    // Each @font-face points at a gstatic woff2; pull it down and rewrite the
    // src to a local path, keeping the unicode-range subsetting intact.
    const urls = [...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2)\)/g)];
    let n = 0;
    const seen = new Map();

    for (const [, remote] of urls) {
      if (seen.has(remote)) continue;
      const file = `${slug(fam.name)}-${n++}.woff2`;
      const bin = await fetch(remote, { headers: { 'User-Agent': UA } });
      if (!bin.ok) throw new Error(`${remote}: ${bin.status}`);
      await writeFile(path.join(OUT_DIR, file), Buffer.from(await bin.arrayBuffer()));
      seen.set(remote, file);
    }

    for (const [remote, file] of seen) {
      css = css.split(`url(${remote})`).join(`url("../assets/fonts/${file}")`);
    }

    blocks.push(`/* ---- ${fam.name} ---- */\n${css.trim()}`);
    console.log(`${fam.name}: ${seen.size} files`);
  }

  const header = `/**
 * Vendored typefaces. Generated by tools/fetch-fonts.mjs — do not edit by hand.
 * Re-run \`node tools/fetch-fonts.mjs\` to refresh.
 */\n\n`;

  await writeFile(CSS_OUT, header + blocks.join('\n\n') + '\n');
  console.log(`wrote ${path.relative(ROOT, CSS_OUT)}`);
}

main().catch((e) => {
  console.error(e.message);
  process.exit(1);
});
